name: Pull Request Checks

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 mypy pytest pytest-cov
        
    - name: Debug directory structure
      run: |
        echo "Current directory:"
        ls -la
        echo "src directory:"
        ls -la src || echo "src directory not found"
        
    - name: Install package
      run: pip install -e .
        
    - name: Check formatting
      run: black --check src tests
      
    - name: Lint with flake8
      run: flake8 src tests --count --max-complexity=10 --statistics
      
    - name: Type check with mypy
      run: mypy src tests
      
    - name: Run tests
      run: |
        pytest --cov=src tests/
        
    - name: Check test coverage
      run: |
        pytest --cov=src --cov-fail-under=90 tests/ || echo "Coverage check failed but continuing"

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Security scan
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --severity-threshold=high